### ISSUE TITLE
Unable to pull JMX data using jolokia from host machine but works inside docker container

### ISSUE THREAD

**Issue by maheshvra** [wurstmeister/kafka-docker#193]
I have added jolokia agent in libs directory. When kafka starts, it exposes JMX metrics using jolokia.
`COPY ./jolokia-jvm-1.3.6-agent.jar /opt/kafka/libs/jolokia-jvm-1.3.6-agent.jar
RUN chmod a+x /opt/kafka/libs/jolokia-jvm-1.3.6-agent.jar`

When i do `http://localhost:8778/jolokia/list` within docker container, i am able to get desired output.

```
curl -v "http://localhost:8778/jolokia/list"
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8778 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8778 (#0)
> GET /jolokia/list HTTP/1.1
> Host: localhost:8778
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Pragma: no-cache
< Date: Sat, 10 Jun 2017 20:11:02 GMT
< Transfer-encoding: chunked
< Content-type: text/plain; charset=utf-8
< Expires: Sat, 10 Jun 2017 19:11:02 GMT
< Cache-control: no-cache
```

However when i do from host machine, it does not work.

**Comment by vikramraman** [comment]
@maheshveera The issue is that Jolokia is only exposed over localhost within the container, not the docker bridge ip:

`tcp        0      0 ::ffff:127.0.0.1:8778   :::*                    LISTEN      1/java`

To fix that, add `=host=*` to the docker-compose.yml as below:

`-javaagent:/opt/kafka/libs/jolokia-jvm-1.3.6-agent.jar=host=*`

If you now run netstat in your container:
`tcp        0      0 :::8778                 :::*                    LISTEN      1/java`

The curl command will now work from the host machine.

**Comment by sscaling** [comment]
@maheshvra  - This sounds like an issue unrelated to the kafka-docker image, but a general jolokia/docker configuration question. If @vikramraman's answer doesn't help perhaps try the jolokia and/or docker mailing lists?
