### ISSUE TITLE
Link between 'latest' tag and Kafka version

### ISSUE THREAD

**Issue by louisledev** [wurstmeister/kafka-docker#210]
Hi,

We want to integrate this docker image in our build. However, we have to ship and maintain multiple versions of our software. Therefore, we want to have a good understanding of which version of Kafka is running in each of our release version, and currently, we don't understand which version of kafka corresponds to the image tagged 'latest'. 
My understanding is that you tag the latest release of the docker image as 'latest' (and versioned all the older ones) but you don't provide an equivalent image tagged with the corresponding version.  
Would it be possible to have two images, one tagged 'latest' and one tagged with the kafka version?

Thanks for your consideration.

Louis

**Comment by sscaling** [comment]
Hi @louisledev  - I'm not sure if I understand you entirely.

All docker images are tagged and versioned on docker hub: [https://hub.docker.com/r/wurstmeister/kafka/tags/](https://hub.docker.com/r/wurstmeister/kafka/tags/) (built from the corresponding git tags).

Does this answer your question?

**Comment by louisledev** [comment]
Hi,

Thanks for coming back... but it does not really answer my question.
My problem is with the latest image, which is only tagged 'latest'. I would
prefer to want to be able to specify a version for my production and not
'latest'.
So, what I am missing is the proper version for the latest image.

Thanks.

Louis

**Comment by sscaling** [comment]
@louisledev  - could you define what you mean by 'latest' image. Do you mean 'master' ?

If so, I think the standard dockerhub config is to build 'master' as 'latest'. If this is not sufficient, what is the expectation? a git sha in the tag name or something? I think this would quickly create tag-hell in the list of tags, most of which would never be used.

Unfortunately docker hub doesn't support build args, otherwise we could inject the git sha / branch into the image environment for you to check at runtime as another solution. Long running thread [here](https://github.com/docker/hub-feedback/issues/508)

I'd have to check with @wurstmeister for the specific dockerhub config for this repo to confirm the above mentioned config.

I'd recommend sticking to the tagged versions if having stability in your production environment is critical.

I'll have a think to see if there's anything we can do, there could be a non-exact injection of version by looking up the git master reference from the image build process, i.e. calling out to `https://api.github.com/repos/wurstmeister/kafka-docker/git/refs/heads/master` or something. But probably not ideal if you're looking for precision in a production env.

**Comment by MassTroy** [comment]
I have the same issue. Most docker images that are published to hub.docker.com will publish alias docker tags. For example postgres has the tags `latest`, `10`, and `10.3` which are all *currently* the same version. When version 10.4 comes out, the `latest` and `10` tags will be updated to reference it, but `10.3` will never change. I can reference 10.3 in my code and be confident in it never changing.

The `latest` tag for wurstmeister/kafka does not have a corresponding version number tag for the same image. So if I want to work with today's version of the image and keep it as a fixed version in my code, there is no way of doing this. The tags `1.0.1` (the latest numbered version at time of writing) and `latest` should be the same image.

**Comment by sscaling** [comment]
> Most docker images that are published to hub.docker.com will publish alias docker tags

official guidelines here: [https://github.com/docker-library/official-images#tags-and-aliases](https://github.com/docker-library/official-images#tags-and-aliases)

The difference I see in our current model is (where currently 1.0.1 is the newest version available):

*  'latest' references 1.0.1 + any changes to the packaging
* '1.0.1' will never change. 

This is pretty much the git model. A tag should be seen as immutable and `latest` is analogous to `master`.

In theory, we should have very few changes to packaging (just bug fixes). However, we've recently being trying to go through a backlog of bugs and tidy things up.

The main difference between this image and something like Postgres in your example is that we're actually just repackaging a 3rd-party. So where as Postgres docker versions are synonymous with a Postgres application release, our version numbers are actually a version that tries to identify a version of the packaged application. Typically when a new version of Kafka is released, we will tag the repo (assuming that it seems stable) and a build is made. *only* if a bug needs to be back-ported will we create a new release of a previous version of the image, in this case you will see tags such as `0.10.0.1-1` and `0.10.0.1-2` (https://hub.docker.com/r/wurstmeister/kafka/tags/).

For example, if we'd just updated the 1.0.1 build recently, we would have introduce some breaking changes. For anyone pointing to a stable 1.0.1 tag, this could have broken their deployments.

I think the issue that should be more important to you is: https://github.com/wurstmeister/kafka-docker/issues/163.

Once this is done, we will most likely change docker builds to be performed by travis so we have more control, but will hopefully automatically back-port changes into older branches (after-all it should only be the binary that changes really).

Because many things have changed, this probably still means that we cannot simply update the `0.8.2.0` tag, so we still need a strategy for relating our packaging version against the target application bundled. This is another problem to solve / question to answer.

**Comment by rafis** [comment]
@wurstmeister please tag images with version of zookeeper. plz.
