### ISSUE TITLE
Number of alive brokers '0' does not meet the required replication factor '1' for the offsets topic

### ISSUE THREAD

**Issue by softwarevamp** [wurstmeister/kafka-docker#218]
ERROR [KafkaApi-1002] Number of alive brokers '0' does not meet the required replication factor '1' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)

but this message keeps up till forever

thanks for help

**Comment by terekcampbell** [comment]
+1 same issue

**Comment by softwarevamp** [comment]
what is your command run docker kafka?

**Comment by barutm** [comment]
same issue

**Comment by victorzapatasantex** [comment]
Same issue. I'm running Kafka with `bin/kafka-server-start.sh config/server.properties`

**Comment by shardedbrain** [comment]
+1

**Comment by pineappleDev** [comment]
same issue

**Comment by ivanopagano** [comment]
+1

**Comment by jjoller** [comment]
+1

**Comment by MartyPang** [comment]
same issue

**Comment by ivanopagano** [comment]
I solved by using the same port internally and outside the container, without remapping.
This seems to make the broker accessible both for internal processes and external clients

**Comment by boedy** [comment]
I had the same issue, and took a day to figure out. For me it had to do with the [listener configuration](https://github.com/wurstmeister/kafka-docker#listener-configuration). The reason I got this error, is because the address stored in zookeeper for the the INSIDE protocol was not reachable by the other brokers.

To check if this is the case:
1. Ssh into broker
2. Connect to zookeeper: `/opt/kafka/bin/zookeeper-shell.sh`
3. Check available brokers: `ls /brokers/ids/`
4. Get broker config: `get /brokers/ids/<broker id>`
5. Check to see which address is listed for inside protocol and check if this address can be pinged from all brokers

I solved this by modifying [this line](https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L50) to:
```
export ADD_LISTENER="${KAFKA_PROTOCOL_NAME}://${KAFKA_HOST_NAME-$(hostname -i)}:${KAFKA_PORT}"
```

**Comment by sscaling** [comment]
@softwarevamp - please can you include the docker-compose file, docker versions, os version and kafka startup log?

**Comment by sscaling** [comment]
Closing due to staleness. Please reopen if this persists.

**Comment by viniciusntch** [comment]
Just add those lines into server.properties

offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

**Comment by kingmorning** [comment]
I found the reason, if you enabled the SASL, you need to use SASL protocol for the security.inter.broker.protocol, that's because SASL can provider user info, PLAINTEXT or SSL can not provide user info.  when enabled the SASL, the cluster need user info to check the privileges.

you can modify conf/log4j.properties, enable the authorizer log.

log4j.logger.kafka.authorizer.logger=DEBUG, authorizerAppender
log4j.additivity.kafka.authorizer.logger=true

you will find the reason, when you start the broker.

**Comment by prasadprabhu333** [comment]
I faced the same issue running the Confluent Kafka docker version 3.3.1. Producers can connect and publish data totally fine but consumers cannot subscribe to any topics. I have SSL configured but not SASL.
If you're using docker, when kafka starts up, its not using the default server.properties but rather kafka.properties which is generated when the container is getting instantiated from the image. The way to provide an input is to pass a parameter to the docker.
In my docker-compose.yml, i added this property and the errors went away.
```KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1```

**Comment by giladsh1** [comment]
had the same issue - make sure the brokers can "talk" to one another via port 9092

**Comment by SandyChapman** [comment]
This can also happen if you've enabled SASL between the brokers without giving proper access (such as making a `super.user` entry in your server.properties.

```
super.users=User:admin
```

**Comment by realpeanut** [comment]
Another possible reason is that the listeners configuration and the advertised.listeners configuration specify different values. Modifying to the same value can solve the problem.
