### ISSUE TITLE
Unable to build kafka docer in mac and returns zero code :4

### ISSUE THREAD

**Issue by hero0926** [wurstmeister/kafka-docker#237]
It occurs like

```
Step 8/16 : RUN chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka
 ---> Running in 283e86f93a81
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka' returned a non-zero code: 4
```

i guess it's because of permission problem, but with sudo command, it also won't build.

**Comment by naouss80** [comment]
The .sh files are in dos format.
You should use dos2unix to convert them to unix format

**Comment by hero0926** [comment]
@naouss80 I suppose it's usuall problem for mac os users maybe README.md needs to mention it. Anyway, Thx

**Comment by AndrewOrr** [comment]
Looks like the issue comes form  download-kafka.sh. The mirror that it is looking for no longer returns properly. 
`$ curl --stderr /dev/null https://www.apache.org/dyn/closer.cgi\?as_json\=1                                                                                                                                                                                          [12:38:13]
<HTML><HEAD>
<TITLE>Redirect</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Redirect (authentication_redirect_to_virtual_host)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
You are being redirected to the authentication virtual host.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">

</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>`

So mirror isn't set. There should be a check before it fails on the wget so that it bails early if parsing fails. Something like: 

`if [ "X$mirror" == 'X' ]
 then
    echo "Mirror not set?"
    exit 1
fi`

Anyway, if you manually set the the url, it works: 

`url="http://apache.claz.org/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz"`

**Comment by hero0926** [comment]
@AndrewOrr Hey oh god thanks soooo much. I was borthering but it would helpful. thank you for your answer.

**Comment by sscaling** [comment]
It seems like this was a temporary problem with the apache URL, all seems working for me now, and no other complaints on this specific issue.

This issue does not seem mac specific. It seems like it would be useful to display the error message if the mirror was not found, will raise a PR
