### ISSUE TITLE
unable to create topics: KAFKA_ZOOKEEPER_CONNECT not set

### ISSUE THREAD

**Issue by ericychoi** [wurstmeister/kafka-docker#250]
At some point `create-topics.sh` started breaking with an error

>kafka_1             | Exception in thread "main" org.I0Itec.zkclient.exception.ZkException: Unable to connect to --replication-factor

We realized this is happening because `$KAFKA_ZOOKEEPER_CONNECT` is not set when `create-topics.sh `runs in [this line](https://github.com/wurstmeister/kafka-docker/blob/f3d12b004ebf6a94baa2db20c6650691fc4773da/create-topics.sh#L33). (we are running 1.0).   `create-topics.sh` runs before the variable is [set](https://github.com/wurstmeister/kafka-docker/blob/f3d12b004ebf6a94baa2db20c6650691fc4773da/start-kafka.sh#L7).

A workaround for now is manually set `$KAFKA_ZOOKEEPER_CONNECT` as part of docker-compose.yml.

**Comment by tcjennings** [comment]
That "workaround" is actually the best practice since 'zookeeper.connect' is the canonical name of the configuration setting and `KAFKA_ZOOKEEPER_CONNECT` is the way to express that setting in the environment given the operation of this container.

The alternative `ZK.*PORT_2181_TCP` construction only works if

- you have not moved zookeeper from port 2181
- you use container linking which is legacy and deprecated in favor of more robust docker networking features.
- you use version 1 compose files, which are largely incompatible with modern docker builds and orchestrators like swarm.
- your zookeeper service is named 'zk' or you go out of your way to alias the name in the link setup

I would advocate the removal of the alternative link-based ZK identification from the startup script entirely and require the use of the `KAFKA_ZOOKEEPER_CONNECT` variable.

**Comment by sscaling** [comment]
> I would advocate the removal of the alternative link-based ZK identification from the startup script entirely and require the use of the KAFKA_ZOOKEEPER_CONNECT variable.

@tcjennings  - I agree that the deprecated linking environment variables are not of much use. All the example docker-compose.yml files rely on the dns resolution for the 'zookeeper' hostname, and it seems unlikely that this would break any production deployments (as they shouldn't be using deprecated linking). @wurstmeister - Happy to remove the `KAFKA_ZOOKEEPER_CONNECT`  var and make it a mandatory input?
