### ISSUE TITLE
Specifying multiple zookeeper node information to KAFKA_ZOOKEEPER_CONNECT

### ISSUE THREAD

**Issue by beingamarnath** [wurstmeister/kafka-docker#359]
How to specify multiple zookeeper endpoints to KAFKA_ZOOKEEPER_CONNECT. I have three zookeeper nodes running and I want to connect kafka to it. 

Zookeeper runs in docker swarm mode and are accessible via service names zk1, zk2 and zk3. For this i use official zookeeper image from docker hub.

For now I specify KAFKA_"ZOOKEEPER_CONNECT: zk1:2181" and i want to provide redundancy. Is it possible with this image?

**Comment by sscaling** [comment]
this docker image just maps the `KAFKA_<name>` environment vars to the `<name>` canonical kafka broker configuration keys. In your case, you're just configuring the `zookeeper.connect` property (https://kafka.apache.org/documentation/). 

I believe you want just a CSV of hosts:IPs, such as

```
KAFKA_ZOOKEEPER_CONNECT=zk1,zk2,zk3
```

Port shouldn't be necessary when using the standard zookeeper port.

**Comment by samansupriadi** [comment]
i had some problem but after adding multiple zookeeper host to zookeeper.connect.
the kafka become inconsistent like when i restart kafka sometimes it running  sometimes it failed to running i thik it because first restart kafka conenct to the right zookeper then second restart connect to the wrong zookeper and the third restart connect again to the right zookeeper, so the kafka become  inconsistent with error it the log "different ID supposed to be"
