### ISSUE TITLE
Exposing, but not publishing, ports

### ISSUE THREAD

**Issue by mpj** [wurstmeister/kafka-docker#40]
First, this is a great image, thank you so much for your work! 

Now, I'm having trouble understanding how to _expose, but not publish, the kafka ports_?

When I keep the "ports" property as is in my docker-compose.yml, everything works dandy. However, I don't really want to expose kafka for all to see - I just want my other containers to see it, so I try to change "ports" to "expose". This causes kafka to break down with a java.lang.NumberFormatException: For input string: "", presumably because Kafka is trying to parse an empty string in some config file where it expects a port. 

How can I use _expose_ instead of _ports_ and still hade Kafka work?

**Comment by b0c1** [comment]
I'm beginner too, but I think you cant... The reason why you need to set the advertised host name, is simple, you can't create cyclic link with kafka...
example:
you set scale=2 to docker compose, now docker compose will create two kafka instance and publish the inner 9092 port to random. The start script will detect the "public" port and set as "advertised port". After that each kafka container will register themselves as advertised host/published port. Zookeeper known each broker and brokers using this for sync

Or maybe somebody correct me...
Or somebody have solution

**Comment by ibizaman** [comment]
Normally there is nothing special to do, see https://github.com/wurstmeister/kafka-docker/issues/38#issuecomment-185590449.

**Comment by markusthoemmes** [comment]
I believe this image lacks an `EXPOSE` command. That might be due to the configurability of the Kafka Port internally. If we agree we should expose 9092, I'll be happy to assemble a PR to fix that. We're using Kafka in a multi docker-host deployment without a Swarm, so linking it not an option.

**Comment by sscaling** [comment]
@mpj  - You should be able to use the [expose](https://docs.docker.com/compose/compose-file/#expose) docker-compose file instruction to achieve this. If you are experiencing a java.lang.NumberFormatException, it is probably because of how the scripts retrieve the port from the docker daemon (i.e. see create-topics.sh / start-kafka.sh). If this is still an issue or pain point please re-open with your docker-compose.yml, version of docker (client + server) and any other relevant information (such as OS). Thanks.

Closing, nearly 3 years old.
