### ISSUE TITLE
Help required configuring listeners

### ISSUE THREAD

**Issue by denis-zhdanov** [wurstmeister/kafka-docker#417]
**edit** (original title) _External & internal connections setup doesn't work_

Hello,

Could you please help me with setting up the `wurstmeister/kafka` docker in a way to access it either from docker or host networks?  

My use-case is to test docker image during CI. I.e. run docker with kafka, zookeeper, target application and then perform the test by sending particular messages to kafka and verifying that there is particular output in kafka.

**docker-compose.yml**

```
 kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:29092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
```

[Here](https://github.com/denis-zhdanov/samples/tree/master/docker/kafka) is a complete standalone example which illustrates the problem:
- [simple kafka client](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/src/main/java/org/denis/KafkaMessageHandler.java) which receives a message in one topic and publishes an echo message to another one
- [docker-compose](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/docker-compose-wurstmeister.yml) which configures *kafka* container to be exposed either to docker or host networks
- [a test](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/src/test/java/org/denis/ApplicationTest.java) which tries to send a message to a kafka running in docker

There is a [script](https://github.com/denis-zhdanov/samples/blob/master/docker/kafka/run-wurstmeister.sh) which automates the whole process.

Zookeeper, kafka and sample client start just fine, external kafka client defined in the test fails:
```
   00:19:52.090 [kafka-producer-network-thread | 07acefbb-3508-4512-be14-859dd7f6917d] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=07acefbb-3508-4512-be14-859dd7f6917d] Initiating connection to node 127.0.0.1:29092 (id: -1 rack: null)
    00:19:52.090 [kafka-producer-network-thread | 07acefbb-3508-4512-be14-859dd7f6917d] DEBUG org.apache.kafka.common.network.Selector - [Producer clientId=07acefbb-3508-4512-be14-859dd7f6917d] Connection with /127.0.0.1 disconnected
    java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:458)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:412)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163)
        at java.lang.Thread.run(Thread.java:748)
```

Could you please advise on why it doesn't work and what should be done to allow either internal (docker network) or external (host network) connections?

**Comment by sscaling** [comment]
> Could you please help me with setting up bitnami kafka docker 

You will need to ask for support from Bitnami - I don't know much about them, but I believe this is exactly what Bitnami does, offer support on packaging things in the cloud.

> My use-case is to test docker image during CI. I.e. run docker with kafka, zookeeper, target application and then perform the test by sending particular messages to kafka and verifying that there is particular output in kafka.

Our (fairly limited) test suite is [here](https://github.com/wurstmeister/kafka-docker/tree/master/test) - executed on [travis-ci](https://travis-ci.org/wurstmeister/kafka-docker). However there are tests for sending / receiving messages via [kafkacat](https://github.com/edenhill/kafkacat)

> Could you please advise on why it doesn't work and what should be done to allow either internal (docker network) or external (host network) connections?

Have you read the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) ?

**Comment by denis-zhdanov** [comment]
Sorry, it was a typo. As you can see in the linked samples, they all use wurstmeister kafka and zookeeper images.  
And yes, I read the connectivity guide. Unfortunately, it doesn't answer the question on how to properly setup two listeners either for internal or external networks

**Comment by sscaling** [comment]
It is better to post all config and relevant information in a ticket so that it is co-located with any answers. I've added the relevant docker-compose to your question and updated the title.

Looking at your configuration, there seems to be at least several problems:

1. Your advertised port is `29092` (I've no idea where this comes from, but it is not exposed by the container - only `9094` is)
2. Your advertised host is `127.0.0.1` which is going to be problematic for multiple brokers (if you don't require multiple brokers - then it's probably simpler to use the `advertised.host` and `advertised.port` configuration)
3. Your client config is `KAFKA_ADDRESS=kafka:9092`. This port is not defined anywhere.

As far as I can tell, at no point does traffic run outside of the docker bridge network (the sample client is a docker image in the same docker-compose project) - so I'm not sure your question is entirely correct - it's just a fundamental setup issue you are having. 

If that is the case, then It's exactly the same scenario as the aforementioned tests. The [docker-compose.yml](https://github.com/wurstmeister/kafka-docker/blob/master/test/docker-compose.yml) just has the brokers, zookeepers and test-services defined that require access to the broker. 

**NOTE:** the docker-compose file is more complex then strictly needed as it runs multiple brokers (hence the disambiguation of the `BROKER_ID`). You can see a client (`kafkacat`) interacting with the brokers in [this](https://github.com/wurstmeister/kafka-docker/blob/master/test/0.0/test.read-write.kafkacat.sh) test.

I would recommend verifying connectivity and setup outside of your custom test code (such as using Kafkacat or the console consumer/producer that comes with Kafka). Once setup is verified, then try integrating your tests.

**Comment by sscaling** [comment]
No response from OP, so closing due to staleness.
