### ISSUE TITLE
while restart kafka or auto restart , the brokers info on zk such as host changed ,which caused producer cannot send message unless restart producer

### ISSUE THREAD

**Issue by Mrchenli** [wurstmeister/kafka-docker#446]
while restart kafka or auto restart , the brokers info on zk such as host changed ,which caused producer cannot send message unless restart producer

**Comment by sscaling** [comment]
This is a configuration issue, not an issue with the image.

You will need to set a consistent broker ID and logs dir, so that the broker can survive restart (You can see examples in the [multi-broker docs](https://kafka.apache.org/documentation/#quickstart_multibroker). These configurations are specified as essential configurations in the [broker config docs](https://kafka.apache.org/documentation/#brokerconfigs).

The `BROKER_ID_COMMAND` and `HOSTNAME_COMMAND` features supported by this image may be off use if you have dynamic hostnames / environments that you need to introspect - otherwise the standard `KAFKA_BROKER_ID` and `KAFKA_LOGS_DIR` environment vars should be sufficient.

**Comment by Mrchenli** [comment]
environment:
      HOSTNAME_COMMAND: "docker info | grep 'Node Address:' | cut -d' ' -f 4"
      KAFKA_ZOOKEEPER_CONNECT: paascloud-provider-zk:2181,paascloud-provider-zk2:2181,paascloud-provider-zk3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://_{HOSTNAME_COMMAND}:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      BROKER_ID_COMMAND: "docker info | grep 'Node Address:' | cut -d' ' -f 4 | cut -d . -f 4"
      KAFKA_LOG_DIRS: /kafka/kafka-logs-{{.Node.Hostname}}
      KAFKA_HOME: /opt/kafka
here is my environment configuration, KAFKA_LOG_DIR volume to a nfs file .
but the hostname is the container's ip which changed once restart

**Comment by sscaling** [comment]
> but the hostname is the container's ip which changed once restart

I would expect it to be the address of the Swarm node, not the container IP from `HOSTNAME_COMMAND: "docker info | grep 'Node Address:' | cut -d' ' -f 4"`

If you meant that the logs dir uses the containers IP because of the following config:

> KAFKA_LOG_DIRS: /kafka/kafka-logs-{{.Node.Hostname}}

See below:

(I'm **Guessing** that your setup is deployed as a Docker Swarm stack from the limited information you have provided.)

If you are running multiple brokers on a single node then you will need to consistently associate a broker ID to a logs directory. The dynamic hostname/IP created by docker would be bad for this. Most people seem to end up defining 3 separate Kafka services (i.e. `kafka-1`, `kafka-2` etc..) so they can have full, deterministic, control over broker ID and logs dir (i.e. link service name to broker ID and broker ID with logs dir).

Alternatively you could use placement constraints or a [global](https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/#replicated-and-global-services) service (assuming you want as many brokers as you have Swarm nodes) - then make sure your nodes are consistently addressed though DNS / IP allocation, so that this can be parsed and used by the `HOSTNAME_COMMAND` and `BROKER_ID_COMMAND`.

**Comment by Mrchenli** [comment]
thank u for your reply  ^ ^  . i expose port and other services use the OUTSIDE//:9092, logs solved with nfs volume.
