### ISSUE TITLE
Can't connect wurstmeister/Kafka listener

### ISSUE THREAD

**Issue by MrMedTech** [wurstmeister/kafka-docker#468]
Hi,
I know this issue has been discussed befor but I can't get it done:
I try to setup a docker-compose with Kafka @ Wurstmeister.

**SCENARIO:**
I develop an Architecture of multiple microservices. In concrete: I have a spring boot app that sends JSON to my kafka broker. A Flask service consumes the data.
This works when running the whole think outside docker. I am also able to send data to the kafka Topic in docker.

**CODE:**
Flask:

    KafkaHost = "kafka:9092"
    def initkafka():
        # connect to Kafka server and pass the topic we want to consume
        consumer = KafkaConsumer("TEST",
                                 group_id='view',
                                 bootstrap_servers=[Constants.KafkaHost]
                                 )
        KafkaConsumer(auto_offset_reset='latest',
                      enable_auto_commit=False)
    
        KafkaConsumer(value_deserializer=lambda m: json.loads(m.dedoce('utf-8')))
        KafkaConsumer(consumer_timeout_ms=1000)
        return consumer

Docker Compose:

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - "2181:2181"
        networks:
          - test-net
  
      kafka:
        image: wurstmeister/kafka
        ports:
          - "9092:9092"
        environment:
          KAFKA_PORT: 9092
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "SQUARE:1:1"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
          - zookeeper
        networks:
          - test-net

**ERROR**

    Traceback (most recent call last):
      File "run.py", line 1, in <module>
        from controller import Controller
      File "/app/controller/Controller.py", line 27, in <module>
        consumer = KafkaConfig.initkafka()
      File "/app/config/KafkaConfig.py", line 16, in initkafka
        enable_auto_commit=False)
      File "/usr/local/lib/python3.6/site-packages/kafka/consumer/group.py", line 324, in __init__
        self._client = KafkaClient(metrics=self._metrics, **self.config)
      File "/usr/local/lib/python3.6/site-packages/kafka/client_async.py", line 221, in __init__
        self.config['api_version'] = self.check_version(timeout=check_timeout)
      File "/usr/local/lib/python3.6/site-packages/kafka/client_async.py", line 826, in check_version
        raise Errors.NoBrokersAvailable()
    kafka.errors.NoBrokersAvailable: NoBrokersAvailable

I think that it is a problem of the environment configuration. I've read the wurstmeister doc but I can't figure out what I need to setup to make my flask service find the kafka broker. 
The logs say that kafka is up an running und the topic " TEST " gets is created.
Do I have to configure the listeners e.g. say with ip and port in my network will listen to kafka ? Because in the [kafka docs][1] advertised.listeners is described as 

> Listeners to publish to ZooKeeper for clients to use, if different than the listeners config property. In IaaS environments, this may need to be different from the interface to which the broker binds. If this is not set, the value for listeners will be used. Unlike listeners it is not valid to advertise the 0.0.0.0 meta-address.

  [1]: https://kafka.apache.org/documentation/#consumerapi

**Comment by sscaling** [comment]
```
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
```

In your one-broker test setup, this means that when your client connects to a broker to list the meta-data for a topic (which partition belongs to which broker), it will retrieve the information from zookeeper and tell the client that it is available at `kafka:9092`. This is fine inside the docker network as `kafka` is resolvable. Outside, unless you have configured DNS or static `/etc/hosts/` entry, there is no way for your client to know where the `kafka` host is.

Assuming Unix as the host OS, you should be able to run `ifconfig` from terminal, and use the LAN IP instead of `kafka`, i.e.

```
$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	inet 127.0.0.1 netmask 0xff000000 
        ... snip ...
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	inet 192.168.1.67 netmask 0xfffffff0 broadcast 192.168.1.79
	... snip ...
```

This would equate to

```
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.67:9092
```

As described in the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) - this allows clients inside and outside of the docker network to connect to the broker via your public interface (traffic is forwarded to the docker bridge because of the "9092:9092" published ports)

There are obviously other tricks you can do, such as add a `127.0.0.1 kafka` entry to your `/etc/hosts` file, but normally better to avoid changing system configuration just for testing an app.
