### ISSUE TITLE
kafka-docker-master_zookeeper_1 exited with code 0

### ISSUE THREAD

**Issue by jhebelerDS** [wurstmeister/kafka-docker#472]
```
jhebeler@AdvancedAnalytics1:~/docker-compose/kafka-docker-master$ docker-compose -f docker-compose-single-broker.yml up 
Starting kafka-docker-master_kafka_1     ... done
Starting kafka-docker-master_zookeeper_1 ... done
Attaching to kafka-docker-master_kafka_1, kafka-docker-master_zookeeper_1
kafka_1      | waiting for kafka to be ready
kafka_1      | [Configuring] 'advertised.port' in '/opt/kafka/config/server.properties'
kafka_1      | Excluding KAFKA_HOME from broker config
kafka_1      | [Configuring] 'advertised.host.name' in '/opt/kafka/config/server.properties'
kafka_1      | [Configuring] 'port' in '/opt/kafka/config/server.properties'
kafka_1      | [Configuring] 'broker.id' in '/opt/kafka/config/server.properties'
kafka_1      | Excluding KAFKA_VERSION from broker config
kafka_1      | [Configuring] 'zookeeper.connect' in '/opt/kafka/config/server.properties'
kafka_1      | [Configuring] 'log.dirs' in '/opt/kafka/config/server.properties'
kafka-docker-master_zookeeper_1 exited with code 0
```

Given that zookeeper is dead - the rest fails..
Any ideas on what is causing this?  I also went in and correct the permissions on the SSH keys but that stopped the warnings but that was all.  Thank you!

**Comment by jhebelerDS** [comment]
I substituted a standard zookeeper container and I got it to mostly work.  Except when I got to the testing.  I can create topics and get their status.  But when i attempt to create a producer it seems to create a strange URL that contains the host:port:port - here is the error message
WARN Couldn't resolve server localhost:2181:32783 from bootstrap.servers as DNS resolution failed for localhost:2181 (org.apache.kafka.clients.ClientUtils).  Likewise when i tried to create consumer you have zookeeper as an option but when i ran the instruction it failed as follows
bash-4.4# $KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --zookeeper=172.20.0.1:2181
zookeeper is not a recognized option

Ideas?  Thanks

**Comment by sscaling** [comment]
You have not included any relevant information for anyone to provide help.

I would suggest by starting with your configuration (docker run command / docker-compose file) along with versions of Image, Docker daemon and host OS etc.

As an aside, I've no idea where SSH keys come into the an issue with the kafka-docker image. The image does not explicitly configure/use SSH.

`host:port:port` mapping looks like the `<host>:<published port>:<proxied port>` format, given the 32xxx range. So that is probably an issue with the HOSTNAME_COMMAND if used. If not that, could potentially be an image issue with the bootstrap process, but without the above information it would just be guess work.

**Comment by mmacheerpuppy** [comment]
Do not use this without understanding the implication it gives a user "wurstmeister" root access to your system.

**Comment by sscaling** [comment]
Closing due to no response from OP.
