### ISSUE TITLE
Add UI containers

### ISSUE THREAD

**Issue by oswee** [wurstmeister/kafka-docker#527]
Would be great to add Landoop or other UI layer.

Not an big issue to add by hand, but... it would make this repo more complete.
"kafka-docker-suite"

**Comment by sscaling** [comment]
As far as i'm aware these are all side-car type applications that run in a separate container. These should therefore be packaged and maintained independently of this repo. 

Also in the case of the Landoop, depending on which tool you use, you may need a specfic Kafka distribution (such as confluent - not the one in this repo).

Typically we've tried to stay away from any recommendations or integrations as we purely package the Apache Kafka binary.

However, if you have some standard, battle-hardened, patterns that you want to share then we can discuss further the best place for these - otherwise can we close this issue?
